"""Per-model Bitmoji feature configuration.

Lets each model override which option the automation picks for a face/makeup
feature (hair, eyes, nose, jaw, lips, skin, makeup, earrings, chest) — either a
**fixed** option or a **random** pick from a chosen pool. Unconfigured features
fall back to the hardcoded presets in ``snap_selectors/selectors.py`` so nothing
changes until the operator edits a model in the dashboard.

Single source of truth for:
  * ``FEATURES`` — the configurable features, how to extract their option catalog
    from the Bitmoji editor HTML, and the XPath template used to click a chosen
    option in the live editor.
  * The catalog (``data/bitmoji_catalog.json``, generated by
    ``tools/build_bitmoji_catalog.py``).
  * The per-model overrides (``data/bitmoji_models.json``).
"""

from __future__ import annotations

import json
import random
import re
import threading
from copy import deepcopy
from pathlib import Path

from core.process_utils import APP_DATA_DIR

DATA_DIR = APP_DATA_DIR / "data"
CATALOG_PATH = DATA_DIR / "bitmoji_catalog.json"
MODELS_PATH = DATA_DIR / "bitmoji_models.json"
SHARED_OUTFIT_FEATURES = {"outfits", "tops", "bottoms", "dresses", "footwear", "outerwear", "sock"}

# Each feature carries both its catalog-extraction rule and the live-editor click
# template. ``kind`` is "img" (identified by an image-URL query param) or "color"
# (identified by an SVG swatch ``fill``). ``{id}`` in ``pattern`` is the option id
# (a number for img features, a #hex colour for colour features).
FEATURES: dict[str, dict] = {
    "skin_tone": {
        "label": "Skin Tone", "file": "skintone", "kind": "color", "shape": "rect",
        "group": "Skin",
        "pattern": "xpath=//div[contains(@class,'container') and @tabindex='0' and .//*[name()='rect' and @fill='{id}']]",
    },
    "hair_style": {
        "label": "Hair Style", "file": "hairstyle", "kind": "img", "path": "hair", "param": "hair",
        "group": "Hair",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'hair={id}')]]",
    },
    "hair_color": {
        "label": "Hair Color", "file": "hair color", "kind": "img", "path": "hair", "param": "hair_tone",
        "group": "Hair",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'hair_tone={id}')]]",
    },
    "hair_treatment": {
        "label": "Hair Treatment", "file": "hair treatment", "kind": "img", "path": "hair", "param": "hair_treatment_tone",
        "group": "Hair",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'hair_treatment_tone={id}')]]",
    },
    "eye_shape": {
        "label": "Eye Shape", "file": "eye shape", "kind": "img", "path": "eye", "param": "eye",
        "group": "Eyes",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'/avatar/eye?') and contains(@src,'eye={id}')]]",
    },
    "eye_size": {
        "label": "Eye Size", "file": "eye size", "kind": "img", "path": "eye", "param": "eye_size",
        "group": "Eyes",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'eye_size={id}')]]",
    },
    "eye_spacing": {
        "label": "Eye Spacing", "file": "eye spacing", "kind": "img", "path": "eye", "param": "eye_spacing",
        "group": "Eyes",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'eye_spacing={id}')]]",
    },
    "eye_color": {
        "label": "Eye Color", "file": "eye color", "kind": "color", "shape": "circle",
        "group": "Eyes",
        "pattern": "xpath=//*[name()='svg' and contains(@class,'iris') and @tabindex='0' and .//*[name()='circle' and @fill='{id}']]",
    },
    "eye_lashes": {
        "label": "Eyelashes", "file": "eyelashes", "kind": "img", "path": "eye", "param": "eyelash",
        "group": "Eyes",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'eyelash={id}')]]",
    },
    "eyebrows": {
        "label": "Eyebrows", "file": "eyebrows", "kind": "img", "path": "eyebrows", "param": "brow",
        "group": "Eyes",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'/avatar/eyebrows?') and contains(@src,'brow={id}')]]",
    },
    "eyebrow_color": {
        "label": "Eyebrow Color", "file": "eyebrow color", "kind": "color", "shape": "rect",
        "group": "Eyes",
        "pattern": "xpath=//div[contains(@class,'container') and @tabindex='0' and .//*[name()='rect' and @fill='{id}']]",
    },
    "face_shape": {
        "label": "Face Shape", "file": "face shape", "kind": "img", "path": "face", "param": "face_proportion",
        "group": "Face",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'face_proportion={id}')]]",
    },
    "nose": {
        "label": "Nose", "file": "nose", "kind": "img", "path": "nose", "param": "nose",
        "group": "Face",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'/avatar/nose?') and contains(@src,'nose={id}')]]",
    },
    "jaw": {
        "label": "Jaw", "file": "jaw", "kind": "img", "path": "jaw", "param": "jaw",
        "group": "Face",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'/avatar/jaw?') and contains(@src,'jaw={id}')]]",
    },
    "ears": {
        "label": "Ears", "file": "ears", "kind": "img", "path": "ear", "param": "ear",
        "group": "Face",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'/avatar/ear?') and contains(@src,'ear={id}')]]",
    },
    "lips": {
        "label": "Lips", "file": "lips", "kind": "img", "path": "mouth", "param": "mouth",
        "group": "Face",
        "pattern": "xpath=//div[contains(@class,'head-trait-container') and @tabindex='0' and .//img[contains(@src,'/avatar/mouth?') and contains(@src,'mouth={id}')]]",
    },
    "chest_size": {
        "label": "Chest Size", "file": "chest size", "kind": "img", "path": "mannequin-right", "param": "breast",
        "group": "Body",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'breast={id}')]]",
    },
    "body_shape": {
        "label": "Body Shape", "file": "body shape", "kind": "img", "path": "body-type", "param": "body",
        "group": "Body",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'body={id}')]]",
    },
    "eyeshadow": {
        "label": "Eyeshadow", "file": "eyeshadow", "kind": "color", "shape": "rect",
        "group": "Makeup",
        "pattern": "xpath=//div[contains(@class,'container') and @tabindex='0' and .//*[name()='rect' and @fill='{id}']]",
    },
    "blush": {
        "label": "Blush", "file": "blush", "kind": "color", "shape": "rect",
        "group": "Makeup",
        "pattern": "xpath=//div[contains(@class,'container') and @tabindex='0' and .//*[name()='rect' and @fill='{id}']]",
    },
    "lipstick": {
        "label": "Lipstick", "file": "lipstick", "kind": "color", "shape": "rect",
        "group": "Makeup",
        "pattern": "xpath=//div[contains(@class,'container') and @tabindex='0' and .//*[name()='rect' and @fill='{id}']]",
    },
    "paired_earring": {
        "label": "Earrings", "file": "paired earrings", "kind": "img", "path": "earring-left", "param": "earringL_lobe1",
        "group": "Jewelry & Piercings",
        "pattern": "xpath=//div[contains(@class,'facial-feature-wrapper') and @tabindex='0' and .//img[contains(@src,'earringL_lobe1={id}')]]",
    },
    "nose_piercings": {
        "label": "Nose Piercings", "file": "nose piercings", "kind": "img", "path": "nosering", "param": "nosering_nostrilHighL",
        "group": "Jewelry & Piercings",
        "pattern": "xpath=//div[contains(@class,'facial-feature-wrapper') and @tabindex='0' and .//img[contains(@src,'nosering_nostrilHighL={id}')]]",
    },
    "outfits": {
        "label": "Outfits", "file": "outfits", "kind": "outfit", "path": "top", "param": "top", "color_param": "top_tone1",
        "group": "Outfit",
        "pattern": "xpath=//div[contains(@class,'mix-and-match-container') and @tabindex='0' and .//img[contains(@src,'/avatar/top?') and contains(concat('&',substring-after(@src,'?'),'&'),'&top={id}&')]]",
    },
    "tops": {
        "label": "Tops", "file": "tops", "kind": "outfit", "path": "top", "param": "top", "color_param": "top_tone",
        "group": "Outfit",
        "pattern": "xpath=//div[contains(@class,'mix-and-match-container') and @tabindex='0' and .//img[contains(@src,'/avatar/top?') and contains(concat('&',substring-after(@src,'?'),'&'),'&top={id}&')]]",
    },
    "bottoms": {
        "label": "Bottoms", "file": "bottoms", "kind": "outfit", "path": "bottom", "param": "bottom", "color_param": "bottom_tone",
        "group": "Outfit",
        "pattern": "xpath=//div[contains(@class,'mix-and-match-container') and @tabindex='0' and .//img[contains(@src,'/avatar/bottom?') and contains(concat('&',substring-after(@src,'?'),'&'),'&bottom={id}&')]]",
    },
    "dresses": {
        "label": "Dresses", "file": "dresses", "kind": "outfit", "path": "one_piece", "param": "bottom", "color_param": "bottom_tone1",
        "group": "Outfit",
        "pattern": "xpath=//div[contains(@class,'mix-and-match-container') and @tabindex='0' and .//img[contains(@src,'/avatar/one_piece?') and contains(concat('&',substring-after(@src,'?'),'&'),'&bottom={id}&')]]",
    },
    "footwear": {
        "label": "Footwear", "file": "footwear", "kind": "outfit", "path": "footwear", "param": "footwear", "color_param": "footwear_tone",
        "group": "Outfit",
        "pattern": "xpath=//div[contains(@class,'mix-and-match-container') and @tabindex='0' and .//img[contains(@src,'/avatar/footwear?') and contains(concat('&',substring-after(@src,'?'),'&'),'&footwear={id}&')]]",
    },
    "headwear": {
        "label": "Headwear", "file": "headwear", "kind": "img", "path": "hat", "param": "hat",
        "group": "Accessories",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'hat={id}')]]",
    },
    "outerwear": {
        "label": "Outerwear", "file": "outerwear", "kind": "outfit", "path": "outerwear", "param": "outerwear", "color_param": "outerwear_tone",
        "group": "Outfit",
        "pattern": "xpath=//div[contains(@class,'mix-and-match-container') and @tabindex='0' and .//img[contains(@src,'/avatar/outerwear?') and contains(concat('&',substring-after(@src,'?'),'&'),'&outerwear={id}&')]]",
    },
    "sock": {
        "label": "Socks", "file": "sock", "kind": "img", "path": "sock", "param": "sock",
        "group": "Outfit",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'sock={id}')]]",
    },
    # ---- features discovered by the live editor scan (tools/scan_bitmoji_live.py) ----
    "eye_details": {
        "label": "Eye Details", "file": "eye details", "kind": "img", "path": "eye", "param": "eye_details",
        "group": "Eyes",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'eye_details={id}')]]",
    },
    "cheek_details": {
        "label": "Cheek Details", "file": "cheek details", "kind": "img", "path": "cheek_details", "param": "cheek_details",
        "group": "Face",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'cheek_details={id}')]]",
    },
    "face_lines": {
        "label": "Face Lines", "file": "face lines", "kind": "img", "path": "face_lines", "param": "face_lines",
        "group": "Face",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'face_lines={id}')]]",
    },
    "glasses": {
        "label": "Glasses", "file": "glasses", "kind": "img", "path": "glasses", "param": "glasses",
        "group": "Accessories",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'glasses={id}')]]",
    },
    "earring_left": {
        "label": "Earring (Left)", "file": "earring left", "kind": "img", "path": "earring-left", "param": "earringL_lobe1",
        "group": "Jewelry & Piercings",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'earringL_lobe1={id}')]]",
    },
    "earring_right": {
        "label": "Earring (Right)", "file": "earring right", "kind": "img", "path": "earring-right", "param": "earringR_lobe1",
        "group": "Jewelry & Piercings",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'earringR_lobe1={id}')]]",
    },
    "browring_left": {
        "label": "Brow Ring (Left)", "file": "browring left", "kind": "img", "path": "browring", "param": "browringL_BRing",
        "group": "Jewelry & Piercings",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'browringL_BRing={id}')]]",
    },
    "browring_right": {
        "label": "Brow Ring (Right)", "file": "browring right", "kind": "img", "path": "browring", "param": "browringR_BRing",
        "group": "Jewelry & Piercings",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'browringR_BRing={id}')]]",
    },
    "mouthring": {
        "label": "Mouth Ring", "file": "mouthring", "kind": "img", "path": "mouthring", "param": "mouthring_bottomRingC1",
        "group": "Jewelry & Piercings",
        "pattern": "xpath=//div[@tabindex='0' and .//img[contains(@src,'mouthring_bottomRingC1={id}')]]",
    },
}

# How each feature maps onto the Bitmoji 2D avatar render (the `/avatar/body?`
# preview endpoint), used to draw the live preview. ``(param, is_color)`` — colour
# ids are #hex and must be sent as decimal. Features not listed (makeup, earrings)
# don't visibly change the body render, so the preview ignores them.
RENDER_PARAMS: dict[str, tuple[str, bool]] = {
    "hair_style": ("hair", False),
    "hair_color": ("hair_tone", False),
    "hair_treatment": ("hair_treatment_tone", False),
    "eye_shape": ("eye", False),
    "eye_size": ("eye_size", False),
    "eye_spacing": ("eye_spacing", False),
    "eye_lashes": ("eyelash", False),
    "eye_color": ("pupil_tone", True),
    "eyebrows": ("brow", False),
    "eyebrow_color": ("brow_tone", False),
    "face_shape": ("face_proportion", False),
    "nose": ("nose", False),
    "jaw": ("jaw", False),
    "ears": ("ear", False),
    "lips": ("mouth", False),
    "skin_tone": ("skin_tone", True),
    "chest_size": ("breast", False),
    "body_shape": ("body", False),
    "eyeshadow": ("eyeshadow_tone", True),
    "blush": ("blush_tone", True),
    "lipstick": ("lipstick_tone", True),
    "paired_earring": ("earringL_lobe1", False),
    "nose_piercings": ("nosering_nostrilHighL", False),
    "earring_left": ("earringL_lobe1", False),
    "earring_right": ("earringR_lobe1", False),
    "browring_left": ("browringL_BRing", False),
    "browring_right": ("browringR_BRing", False),
    "mouthring": ("mouthring_bottomRingC1", False),
    # Outfits use the same body-render slot name as a top, but retain independent
    # live catalog records and per-item colour availability.
    "outfits": ("top", False),
    "tops": ("top", False),
    "bottoms": ("bottom", False),
    "dresses": ("bottom", False),
    "footwear": ("footwear", False),
    "headwear": ("hat", False),
    "outerwear": ("outerwear", False),
    "sock": ("sock", False),
    "eye_details": ("eye_details", False),
    "cheek_details": ("cheek_details", False),
    "face_lines": ("face_lines", False),
    "glasses": ("glasses", False),
}

# A neutral front-facing female avatar, used if the catalog carries no captured
# base. Overridden per feature by the model preset + the operator's selections.
DEFAULT_BASE_AVATAR = (
    "https://preview.bitmoji.com/bm-preview/v3/avatar/body"
    "?scale=2&gender=2&style=5&rotation=0"
)

_lock = threading.Lock()

# Cache parsed JSON files (catalog, models) keyed by (path, mtime_ns). The
# Bitmoji catalog is large; re-reading + json.load-ing it for every garment /
# colour operation is a major CPU/memory cost in the Nyxmoji editor. The cache
# keys on mtime so a release-replaced file is picked up immediately, while
# steady-state operations reuse the already-parsed dictionary.
_json_read_cache: dict = {}
_json_read_cache_lock = threading.Lock()


def _invalidate_json_cache() -> None:
    with _json_read_cache_lock:
        _json_read_cache.clear()


def _color_to_decimal(hex_value: str) -> str | None:
    try:
        return str(int(str(hex_value).strip().lstrip("#"), 16))
    except Exception:
        return None


def option_render_value(feature: str, option_id: str):
    """Map a catalog option id onto ``(render_param, value)`` for the avatar URL,
    or ``None`` if the feature doesn't affect the body render."""
    info = RENDER_PARAMS.get(feature)
    value = str(option_id or "").strip()
    if not info or not value:
        return None
    param, is_color = info
    if is_color:
        decimal = _color_to_decimal(value)
        return (param, decimal) if decimal else None
    return (param, value)


def model_presets() -> dict:
    """Per-model baseline avatar params parsed from each model's preset traits in
    ``selectors.py`` — so the live preview starts from the model's real look."""
    try:
        from snap_selectors.selectors import BITMOJI_SELECTORS
    except Exception:
        return {}
    traits = BITMOJI_SELECTORS.get("traits", {})
    models = BITMOJI_SELECTORS.get("models", {})
    out: dict[str, dict] = {}
    for model, mdef in models.items():
        params: dict[str, str] = {}
        for step in (mdef.get("face", []) if isinstance(mdef, dict) else []):
            feature = step.get("step")
            info = RENDER_PARAMS.get(feature)
            sel_key = str(step.get("selector", ""))
            if not info or not sel_key.startswith("traits."):
                continue
            selector = traits.get(sel_key.split(".", 1)[1], "")
            rparam, is_color = info
            if is_color:
                m = re.search(r"fill='#?([0-9a-fA-F]{6})'", selector)
                if m:
                    decimal = _color_to_decimal(m.group(1))
                    if decimal:
                        params[rparam] = decimal
            else:
                sparam = FEATURES.get(feature, {}).get("param", rparam)
                m = re.search(re.escape(sparam) + r"=(\d+)", selector)
                if m:
                    params[rparam] = m.group(1)
        out[model] = params
    return out


def feature_order() -> list[str]:
    """Feature keys ordered by their group, matching the editor's catbar layout."""
    group_order = ["Skin", "Hair", "Eyes", "Face", "Body", "Makeup", "Jewelry & Piercings", "Accessories", "Outfit"]
    grouped: dict[str, list[str]] = {}
    for key, meta in FEATURES.items():
        g = meta.get("group", "")
        grouped.setdefault(g, []).append(key)
    result: list[str] = []
    for g in group_order:
        result.extend(grouped.get(g, []))
    return result


def feature_groups() -> dict[str, list[str]]:
    """Group name to list of feature keys."""
    grouped: dict[str, list[str]] = {}
    for key, meta in FEATURES.items():
        g = meta.get("group", "")
        grouped.setdefault(g, []).append(key)
    return grouped


def render_param_map() -> dict:
    """Catalog-friendly ``{feature: {param, color}}`` for the dashboard preview."""
    return {f: {"param": p, "color": c} for f, (p, c) in RENDER_PARAMS.items()}


def _read_json(path: Path) -> dict:
    try:
        mtime = path.stat().st_mtime_ns
    except OSError:
        return {}
    key = str(path)
    with _json_read_cache_lock:
        cached = _json_read_cache.get(key)
        if cached is not None and cached[0] == mtime:
            return cached[1]
    try:
        data = json.loads(path.read_text(encoding="utf-8-sig"))
    except Exception:
        return {}
    with _json_read_cache_lock:
        _json_read_cache[key] = (mtime, data)
    return data


def _normalize_catalog(data: dict) -> dict:
    """Return a defensive, item-faithful catalog.

    In particular, do not infer an outfit's colours or label from Tops (or any
    other feature): a live garment's record is authoritative, including an
    intentionally empty ``colors`` list.  The function remains intentionally
    idempotent so callers can safely normalize catalog data at every boundary.
    """
    if not isinstance(data, dict):
        return {}
    return data


def _catalog_features(catalog: object) -> dict:
    """Return a feature map from either supported catalog shape."""
    if not isinstance(catalog, dict):
        return {}
    nested = catalog.get("features")
    if isinstance(nested, dict):
        return nested
    return catalog if "features" not in catalog else {}


def catalog_option(feature: str, option_id: str, catalog: dict | None = None) -> dict | None:
    """Return exactly one option record from a raw catalog or feature map."""
    source = load_catalog_raw() if catalog is None else catalog
    feature_data = _catalog_features(source).get(feature)
    options = feature_data.get("options") if isinstance(feature_data, dict) else None
    target = "" if option_id is None else str(option_id).strip()
    if not target or not isinstance(options, (list, tuple)):
        return None
    for item in options:
        item_id = item.get("id") if isinstance(item, dict) else None
        if isinstance(item, dict) and item_id is not None and str(item_id).strip() == target:
            return item
    return None


def option_colors(feature: str, option_id: str, catalog: dict | None = None) -> list[str]:
    """Return only the supplied option's own non-empty colour values."""
    item = catalog_option(feature, option_id, catalog)
    colors = item.get("colors") if isinstance(item, dict) else None
    if not isinstance(colors, (list, tuple)):
        return []
    return [str(color).strip() for color in colors if color is not None and str(color).strip()]


def option_render(
    feature: str,
    option_id: str,
    color: str | dict | None = None,
    catalog: dict | None = None,
) -> dict:
    """Return the supplied option's body params plus its selected colour variant.

    ``catalog`` used to be the third positional argument.  Accept a mapping in
    ``color`` to retain that call form while supporting the new selected-colour
    argument as ``option_render(feature, id, color, catalog)``.
    """
    if isinstance(color, dict) and catalog is None:
        catalog, color = color, None
    item = catalog_option(feature, option_id, catalog)
    render = item.get("render") if isinstance(item, dict) else None
    if not isinstance(render, dict):
        return {}

    params = deepcopy(render.get("params"))
    if not isinstance(params, dict):
        params = {}
    selected = _normalised_colour(color)
    if not selected:
        return params

    for variant_key in ("colour_variants", "color_variants"):
        variants = render.get(variant_key)
        if not isinstance(variants, dict):
            continue
        for variant_color, variant_params in variants.items():
            if _normalised_colour(variant_color) == selected and isinstance(variant_params, dict):
                params.update(deepcopy(variant_params))
                return params
    return params


def _catalog_has_option_list(feature: str, catalog: object) -> bool:
    feature_data = _catalog_features(catalog).get(feature)
    return isinstance(feature_data, dict) and isinstance(feature_data.get("options"), (list, tuple))


def _normalised_colour(value: object) -> str:
    return str(value or "").strip().lower()


def _string_collection(value: object) -> list[str]:
    """Normalize a JSON list/tuple of non-empty strings without iterating scalars."""
    if not isinstance(value, (list, tuple)):
        return []
    return [str(item).strip() for item in value if item is not None and str(item).strip()]


def _valid_selection_colours(feature: str, option_ids: list[str], catalog: object) -> set[str] | None:
    """Return the union of colours offered by a fully-known option pool.

    ``None`` means that at least one selected option is unavailable in the
    catalog, or has not completed a live colour audit, so callers preserve
    configuration rather than discard it.  The scanner records
    ``colors_verified: true`` for every option whose swatches it has audited;
    only then is either a non-empty or empty list authoritative.
    """
    if not _catalog_has_option_list(feature, catalog):
        return None
    known: list[set[str]] = []
    for option_id in option_ids:
        item = catalog_option(feature, option_id, catalog)
        if item is None:
            return None
        if item.get("colors_verified") is not True:
            return None
        colors = {_normalised_colour(color) for color in option_colors(feature, option_id, catalog)}
        known.append(colors)
    if not known:
        return None
    return set().union(*known)


def sanitize_models(models: object, catalog: dict | None = None) -> dict:
    """Normalize model overrides and retain colours only when live data supports them.

    A missing catalog or an unknown option remains non-destructive: normal
    operator configuration is retained.  When an option is known, an empty
    colour list is authoritative and removes fixed/random colour settings.
    """
    if not isinstance(models, dict):
        raise ValueError("models must be a mapping")
    source = load_catalog_raw() if catalog is None else catalog
    normalized: dict[str, dict] = {}
    for model, feature_map in models.items():
        if not isinstance(feature_map, dict):
            continue
        entries: dict[str, dict] = {}
        for feature, selection in feature_map.items():
            if feature in SHARED_OUTFIT_FEATURES:
                continue
            if feature not in FEATURES or not isinstance(selection, dict):
                continue
            mode = str(selection.get("mode") or "").strip().lower()
            if mode == "fixed":
                option_id = str(selection.get("id") or "").strip()
                if not option_id:
                    continue
                entry = {"mode": "fixed", "id": option_id}
                configured = str(selection.get("color") or "").strip()
                allowed = _valid_selection_colours(feature, [option_id], source)
                if configured and (allowed is None or _normalised_colour(configured) in allowed):
                    entry["color"] = configured
                entries[feature] = entry
            elif mode == "random":
                pool = _string_collection(selection.get("pool"))
                if not pool:
                    continue
                entry = {"mode": "random", "pool": pool}
                allowed = _valid_selection_colours(feature, pool, source)
                colors = _string_collection(selection.get("colors"))
                if allowed is None:
                    valid_colors = colors
                else:
                    valid_colors = [color for color in colors if _normalised_colour(color) in allowed]
                if valid_colors:
                    entry["colors"] = valid_colors
                entries[feature] = entry
        if entries:
            normalized[model] = entries
    return normalized


def load_catalog_raw() -> dict:
    """The full catalog file (``features`` + ``base_avatar`` + metadata)."""
    data = _read_json(CATALOG_PATH)
    return _normalize_catalog(data) if isinstance(data, dict) else {}


def load_catalog() -> dict:
    """The option catalog: ``{feature: {type, options: [{id, preview?}], label}}``."""
    return load_catalog_raw().get("features", {})


def load_models() -> dict:
    """Per-model overrides: ``{model: {feature: {mode, id|pool}}}``."""
    data = _read_json(MODELS_PATH)
    return data if isinstance(data, dict) else {}


def save_models(models: object) -> dict:
    """Persist the full per-model override map (validated/normalized)."""
    normalized = sanitize_models(models)
    with _lock:
        DATA_DIR.mkdir(parents=True, exist_ok=True)
        MODELS_PATH.write_text(json.dumps(normalized, indent=2), encoding="utf-8")
    return normalized


def resolve_option(model: str, feature: str, models: dict | None = None) -> str | None:
    """Return the configured option id for ``(model, feature)`` — the fixed id, a
    random pick from the pool, or ``None`` if the feature isn't configured (use
    the hardcoded preset)."""
    source = models if isinstance(models, dict) else (load_models() if models is None else {})
    cfg = source.get(model, {})
    sel = cfg.get(feature) if isinstance(cfg, dict) else None
    if not isinstance(sel, dict):
        return None
    if sel.get("mode") == "fixed":
        return str(sel.get("id") or "").strip() or None
    if sel.get("mode") == "random":
        pool = _string_collection(sel.get("pool"))
        return random.choice(pool) if pool else None
    return None


def resolve_option_color(
    model: str,
    feature: str,
    models: dict | str | None = None,
    option_id: str | dict | None = None,
    catalog: dict | None = None,
) -> str | None:
    """Return a configured colour, constrained to an actual selected item when known.

    The historic third positional ``models`` argument remains supported.  New
    callers can pass ``option_id`` after ``resolve_option`` (and optionally a
    catalog) so random colour selection cannot choose a swatch belonging only
    to a different garment in the pool.
    """
    if isinstance(models, str) and isinstance(option_id, dict):
        models, option_id = option_id, models
    elif isinstance(models, str) and option_id is None:
        models, option_id = None, models

    cfg = (models if isinstance(models, dict) else load_models()).get(model, {})
    sel = cfg.get(feature) if isinstance(cfg, dict) else None
    if not isinstance(sel, dict):
        return None
    allowed: set[str] | None = None
    if option_id is not None:
        source = load_catalog_raw() if catalog is None else catalog
        allowed = _valid_selection_colours(feature, [str(option_id).strip()], source)
    if sel.get("mode") == "fixed":
        color = str(sel.get("color") or "").strip()
        if not color:
            return None
        return color if allowed is None or _normalised_colour(color) in allowed else None
    if sel.get("mode") == "random":
        colors = _string_collection(sel.get("colors"))
        if allowed is not None:
            colors = [color for color in colors if _normalised_colour(color) in allowed]
        return random.choice(colors) if colors else None
    return None


def _xpath_string_literal(value: str) -> str:
    """Quote ``value`` as one safe XPath 1.0 string expression."""
    if "'" not in value:
        return f"'{value}'"
    if '"' not in value:
        return f'"{value}"'

    parts: list[str] = []
    for index, part in enumerate(value.split("'")):
        if part:
            parts.append(f"'{part}'")
        if index < value.count("'"):
            parts.append('"\'"')
    if len(parts) == 1:
        return parts[0]
    return f"concat({', '.join(parts)})"


def _xpath_concat(*expressions: str) -> str:
    """Combine non-empty XPath string expressions without a single argument concat."""
    values = [expression for expression in expressions if expression]
    return values[0] if len(values) == 1 else f"concat({', '.join(values)})"


def _inject_xpath_option_id(pattern: str, option_id: str) -> str | None:
    """Replace ``{id}`` inside XPath literals without raw string interpolation."""
    literal = _xpath_string_literal(option_id)

    def replace_literal(match: re.Match[str]) -> str:
        prefix, suffix = match.groups()
        return _xpath_concat(
            _xpath_string_literal(prefix) if prefix else "",
            literal,
            _xpath_string_literal(suffix) if suffix else "",
        )

    selector = re.sub(r"'([^']*)\{id\}([^']*)'", replace_literal, pattern)
    return None if "{id}" in selector else selector


def build_selector(feature: str, option_id: str, color_id: str | None = None) -> str | None:
    """Build the live-editor click selector for a chosen option id, or ``None``.
    For outfit features, ``color_id`` selects the color swatch."""
    meta = FEATURES.get(feature)
    value = "" if option_id is None else str(option_id).strip()
    if not meta or not value:
        return None
    pattern = meta.get("pattern")
    return _inject_xpath_option_id(pattern, value) if isinstance(pattern, str) else None
